#
#    Copyright (C) 2012-2020 Carl Hetherington <cth@carlh.net>
#
#    This file is part of DCP-o-matic.
#
#    DCP-o-matic is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    DCP-o-matic is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with DCP-o-matic.  If not, see <http://www.gnu.org/licenses/>.
#

import os
import i18n

sources = """
          active_text.cc
          analyse_audio_job.cc
          analyse_subtitles_job.cc
          analytics.cc
          atmos_content.cc
          atmos_mxf_content.cc
          atmos_decoder.cc
          atmos_metadata.cc
          atmos_mxf_decoder.cc
          audio_analyser.cc
          audio_analysis.cc
          audio_buffers.cc
          audio_content.cc
          audio_decoder.cc
          audio_delay.cc
          audio_filter.cc
          audio_filter_graph.cc
          audio_mapping.cc
          audio_merger.cc
          audio_point.cc
          audio_processor.cc
          audio_ring_buffers.cc
          audio_stream.cc
          butler.cc
          text_content.cc
          text_decoder.cc
          case_insensitive_sorter.cc
          check_content_job.cc
          cinema_list.cc
          cinema_sound_processor.cc
          change_signaller.cc
          collator.cc
          colour_conversion.cc
          config.cc
          content.cc
          content_factory.cc
          combine_dcp_job.cc
          copy_dcp_details_to_film.cc
          cover_sheet.cc
          cpu_j2k_encoder_thread.cc
          create_cli.cc
          crop.cc
          cross_common.cc
          curl_uploader.cc
          datasat_ap2x.cc
          dcp_content.cc
          dcp_content_type.cc
          dcp_decoder.cc
          dcp_examiner.cc
          dcp_digest_file.cc
          dcp_film_encoder.cc
          dcp_subtitle.cc
          dcp_subtitle_content.cc
          dcp_subtitle_decoder.cc
          dcp_text_track.cc
          dcp_transcode_job.cc
          dcp_video.cc
          dcpomatic_log.cc
          dcpomatic_socket.cc
          dcpomatic_time.cc
          decoder.cc
          decoder_factory.cc
          decoder_part.cc
          digester.cc
          dkdm_recipient.cc
          dkdm_recipient_list.cc
          dkdm_wrapper.cc
          dolby_cp750.cc
          email.cc
          empty.cc
          encode_cli.cc
          encode_server.cc
          encode_server_finder.cc
          encoded_log_entry.cc
          environment_info.cc
          event_history.cc
          examine_content_job.cc
          examine_ffmpeg_subtitles_job.cc
          exceptions.cc
          export_config.cc
          export_decryption_settings.cc
          fcpxml.cc
          fcpxml_content.cc
          fcpxml_decoder.cc
          frame_info.cc
          file_group.cc
          file_log.cc
          filter_graph.cc
          find_missing.cc
          ffmpeg.cc
          ffmpeg_audio_stream.cc
          ffmpeg_content.cc
          ffmpeg_decoder.cc
          ffmpeg_examiner.cc
          ffmpeg_file_encoder.cc
          ffmpeg_film_encoder.cc
          ffmpeg_image_proxy.cc
          ffmpeg_stream.cc
          ffmpeg_subtitle_stream.cc
          ffmpeg_wrapper.cc
          film.cc
          film_encoder.cc
          film_util.cc
          filter.cc
          font.cc
          font_config.cc
          font_id_allocator.cc
          font_id_map.cc
          frame_interval_checker.cc
          frame_rate_change.cc
          guess_crop.cc
          hints.cc
          http_server.cc
          id.cc
          internet.cc
          image.cc
          image_content.cc
          image_decoder.cc
          image_examiner.cc
          image_filename_sorter.cc
          image_jpeg.cc
          image_png.cc
          image_proxy.cc
          image_store.cc
          internal_player_server.cc
          io_context.cc
          j2k_image_proxy.cc
          job.cc
          job_manager.cc
          j2k_encoder.cc
          j2k_encoder_thread.cc
          j2k_sync_encoder_thread.cc
          json_server.cc
          kdm_cli.cc
          kdm_recipient.cc
          kdm_with_metadata.cc
          kdm_util.cc
          layout_markers.cc
          log.cc
          log_entry.cc
          make_dcp.cc
          map_cli.cc
          maths_util.cc
          memory_util.cc
          mid_side_decoder.cc
          mpeg2_encoder.cc
          named_channel.cc
          overlaps.cc
          pixel_quanta.cc
          player.cc
          player_video.cc
          playlist.cc
          position_image.cc
          ratio.cc
          raw_image_proxy.cc
          reel_writer.cc
          referenced_reel_asset.cc
          release_notes.cc
          remembered_asset.cc
          render_text.cc
          remote_j2k_encoder_thread.cc
          resampler.cc
          resolution.cc
          rgba.cc
          rng.cc
          scoped_temporary.cc
          scp_uploader.cc
          screen.cc
          send_kdm_email_job.cc
          send_notification_email_job.cc
          send_problem_report_job.cc
          server.cc
          shuffler.cc
          state.cc
          spl.cc
          spl_entry.cc
          sqlite_database.cc
          sqlite_statement.cc
          sqlite_table.cc
          sqlite_transaction.cc
          string_log_entry.cc
          string_text_file.cc
          string_text_file_content.cc
          string_text_file_decoder.cc
          subtitle_analysis.cc
          subtitle_film_encoder.cc
          territory_type.cc
          text_ring_buffers.cc
          text_type.cc
          timer.cc
          transcode_job.cc
          trusted_device.cc
          types.cc
          rough_duration.cc
          signal_manager.cc
          stdout_log.cc
          unzipper.cc
          update_checker.cc
          upload_job.cc
          uploader.cc
          upmixer_a.cc
          upmixer_b.cc
          usl.cc
          util.cc
          variant.cc
          verify_dcp_job.cc
          video_content.cc
          video_decoder.cc
          video_encoder.cc
          video_encoding.cc
          video_filter_graph.cc
          video_filter_graph_set.cc
          video_frame_type.cc
          video_mxf_content.cc
          video_mxf_decoder.cc
          video_mxf_examiner.cc
          video_range.cc
          video_ring_buffers.cc
          writer.cc
          zipper.cc
          """

def build(bld):
    if bld.env.STATIC_DCPOMATIC:
        obj = bld(features = 'cxx cxxstlib')
    else:
        obj = bld(features = 'cxx cxxshlib')

    obj.name = 'libdcpomatic2'
    obj.export_includes = ['..']
    obj.uselib = """
                 AVCODEC AVUTIL AVFORMAT AVFILTER SWSCALE
                 BOOST_FILESYSTEM BOOST_THREAD BOOST_DATETIME BOOST_SIGNALS2 BOOST_REGEX
                 SAMPLERATE POSTPROC TIFF SSH DCP CXML GLIB LZMA XML++
                 CURL ZIP BZ2 FONTCONFIG PANGOMM CAIROMM XMLSEC SUB ICU NETTLE PNG JPEG LEQM_NRT
                 LIBZ SQLITE3
                 """

    if bld.env.TARGET_OSX:
        obj.framework = ['IOKit', 'Foundation', 'DiskArbitration', 'ApplicationServices']

    obj.source = sources + ' version.cc'

    if bld.env.ENABLE_DISK:
        obj.source += ' copy_to_drive_job.cc disk_writer_messages.cc ext.cc nanomsg.cc'
        obj.uselib += ' LWEXT4 NANOMSG'
        if bld.env.TARGET_LINUX:
            obj.uselib += ' POLKIT'

    if bld.env.ENABLE_GROK:
        obj.source += ' grok_j2k_encoder_thread.cc grok/util.cc'

    if bld.env.TARGET_WINDOWS_64 or bld.env.TARGET_WINDOWS_32:
        obj.uselib += ' WINSOCK2 DBGHELP SHLWAPI MSWSOCK BOOST_LOCALE SETUPAPI OLE32 UUID'
        obj.source += ' cross_windows.cc i18n_setup_windows.cc'
    if bld.env.TARGET_OSX:
        obj.source += ' cross_osx.cc cross_unix.cc i18n_setup_osx.cc'
    if bld.env.TARGET_LINUX:
        obj.source += ' cross_linux.cc cross_unix.cc i18n_setup_linux.cc'
    if bld.env.STATIC_DCPOMATIC:
        obj.uselib += ' XMLPP'

    obj.target = 'dcpomatic2'

    i18n.po_to_mo(os.path.join('src', 'lib'), 'libdcpomatic2', bld)

def pot(bld):
    i18n.pot(os.path.join('src', 'lib'), sources + " copy_to_drive_job.cc util.h", 'libdcpomatic')

def pot_merge(bld):
    i18n.pot_merge(os.path.join('src', 'lib'), 'libdcpomatic')
