def configure(conf):
    boost_test_suffix=''
    if conf.env.TARGET_WINDOWS:
        boost_test_suffix='-mt'

    conf.check_cxx(fragment = """
                              #define BOOST_TEST_MODULE Config test\n
    			      #include <boost/test/unit_test.hpp>\n
                              int main() {}
                              """, msg = 'Checking for boost unit testing library', lib = 'boost_unit_test_framework%s' % boost_test_suffix, uselib_store = 'BOOST_TEST')

def build(bld):
    obj = bld(features = 'cxx cxxprogram')
    obj.name   = 'unit-tests'
    obj.uselib = 'BOOST_TEST DCP OPENJPEG AVFORMAT AVFILTER AVCODEC AVUTIL SWSCALE POSTPROC CXML'
    obj.use    = 'libdvdomatic'
    obj.source = 'test.cc'
    obj.target = 'unit-tests'
    obj.install_path = ''
