#
#    Copyright (C) 2012-2016 Carl Hetherington <cth@carlh.net>
#
#    This file is part of DCP-o-matic.
#
#    DCP-o-matic is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    DCP-o-matic is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with DCP-o-matic.  If not, see <http://www.gnu.org/licenses/>.
#

import os

def build(bld):
    # Linux application icons
    if bld.env.TARGET_LINUX:
        for r in [16, 22, 32, 48, 64, 128, 256, 512]:
            for p in ['dcpomatic2', 'dcpomatic2_kdm', 'dcpomatic2_server', 'dcpomatic2_batch', 'dcpomatic2_player']:
                bld.install_files('${PREFIX}/share/icons/hicolor/%dx%d/apps' % (r, r), 'linux/%d/%s.png' % (r, p))

    # Install stuff for POSIX systems
    if not bld.env.TARGET_WINDOWS:
        bld.install_as('${PREFIX}/share/dcpomatic2/dcpomatic2_server_small.png', 'linux/16/dcpomatic2.png')
        bld.install_files('${PREFIX}/share/dcpomatic2', 'splash.png')
        bld.install_files('${PREFIX}/share/dcpomatic2', 'zoom.png')
        bld.install_files('${PREFIX}/share/dcpomatic2', 'zoom_all.png')
        bld.install_files('${PREFIX}/share/dcpomatic2', 'select.png')
        bld.install_files('${PREFIX}/share/dcpomatic2', 'snap.png')
        bld.install_files('${PREFIX}/share/dcpomatic2', 'sequence.png')
