#
#    Copyright (C) 2012-2016 Carl Hetherington <cth@carlh.net>
#
#    This file is part of DCP-o-matic.
#
#    DCP-o-matic is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    DCP-o-matic is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with DCP-o-matic.  If not, see <http://www.gnu.org/licenses/>.
#

import os

def build(bld):
    # Linux application icons
    if bld.env.TARGET_LINUX and not bld.env.DISABLE_GUI:
        for r in [16, 22, 32, 48, 64, 128, 256, 512]:
            for p in [
                'dcpomatic2',
                'dcpomatic2_kdm',
                'dcpomatic2_server',
                'dcpomatic2_batch',
                'dcpomatic2_player',
                'dcpomatic2_playlist',
                'dcpomatic2_disk',
                'dcpomatic2_combiner',
                'dcpomatic2_editor']:
                bld.install_files('${PREFIX}/share/icons/hicolor/%dx%d/apps' % (r, r), 'linux/%d/%s.png' % (r, p))

    # Install stuff for POSIX systems
    if not bld.env.TARGET_WINDOWS_64 and not bld.env.TARGET_WINDOWS_32 and not bld.env.DISABLE_GUI:
        bld.install_as('${PREFIX}/share/dcpomatic2/dcpomatic2_server_small.png', 'linux/16/dcpomatic2.png')
        for icon in (
            'splash.png',
            'zoom_white.png',
            'zoom_black.png',
            'select_white.png',
            'select_black.png',
            'snap_white.png',
            'snap_black.png',
            'sequence_white.png',
            'sequence_black.png',
            'zoom_all_white.png',
            'zoom_all_black.png',
            'me.jpg',
            'tick.png',
            'no_tick.png',
            'link.png',
            'add_black.png',
            'add_white.png',
            'pause_black.png',
            'pause_white.png'):
            bld.install_files('${PREFIX}/share/dcpomatic2', icon)
