#
#    Copyright (C) 2015 Carl Hetherington <cth@carlh.net>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#

def build(bld):
    for r in [16, 22, 32, 48, 64, 128, 256, 512]:
        bld(rule='inkscape -C -z -e ${TGT} -w %d -h %d -D ${SRC}' % (r, r), source='dcpomatic2.svg', target='%d/dcpomatic2.png' % r)
        bld.install_files('${PREFIX}/share/icons/hicolor/%dx%d/apps' % (r, r), '../build/graphics/%d/dcpomatic2.png' % r)
