#!/bin/bash

export MINGW_CXX="i686-w64-mingw32-g++"
export MINGW_WINDRES="i686-w64-mingw32-windres"
export MINGW_STRIP="i686-w64-mingw32-strip"
export MINGW_PREFIX="/usr/i686-w64-mingw32"
export WINDOWS_PREFIX="/home/carl/src/windows"

export PKG_CONFIG_LIBDIR=$WINDOWS_PREFIX/lib/pkgconfig

./waf
if [ "$?" != "0" ]; then
  exit 1
fi

d=`pwd`

cp build/windows/installer.nsi build/windows/installer2.nsi

$MINGW_STRIP build/src/tools/dvdomatic.exe -o build/src/tools/dvdomatic.exe.tmp
mv build/src/tools/dvdomatic.exe.tmp build/src/tools/dvdomatic.exe
$MINGW_STRIP build/src/wx/dvdomatic-wx.dll -o build/src/wx/dvdomatic-wx.dll.tmp
mv build/src/wx/dvdomatic-wx.dll.tmp build/src/wx/dvdomatic-wx.dll
$MINGW_STRIP build/src/lib/dvdomatic.dll -o build/src/lib/dvdomatic.dll.tmp
mv build/src/lib/dvdomatic.dll.tmp build/src/lib/dvdomatic.dll

sed -i "s~%resources%~$d/windows~g" build/windows/installer2.nsi
sed -i "s~%deps%~$WINDOWS_PREFIX~g" build/windows/installer2.nsi
sed -i "s~%binaries%~$d/build~g" build/windows/installer2.nsi

makensis build/windows/installer2.nsi
