#!/bin/bash

export MINGW_CXX="i686-w64-mingw32-g++"
export MINGW_WINDRES="i686-w64-mingw32-windres"
export MINGW_PREFIX="/usr/i686-w64-mingw32"
export WINDOWS_PREFIX="/home/carl/src/windows"

export PKG_CONFIG_LIBDIR=$WINDOWS_PREFIX/lib/pkgconfig

./waf
if [ "$?" != "0" ]; then
  exit 1
fi

d=`pwd`

cp build/windows/installer.nsi build/windows/installer2.nsi

sed -i "s~%resources%~$d/windows~g" build/windows/installer2.nsi
sed -i "s~%deps%~$WINDOWS_PREFIX~g" build/windows/installer2.nsi
sed -i "s~%binaries%~$d/build~g" build/windows/installer2.nsi

makensis build/windows/installer2.nsi
