#!/bin/bash

FFMPEGS=/home/carl/ffmpeg

# 0.6, 0.7, 0.8 need significant work, I think.

for v in 0.9.2 0.10.4 0.11.1; do
    PKG_CONFIG_PATH=$FFMPEGS/$v/lib/pkgconfig ./waf configure
    if [ "$?" != "0" ]; then
        echo "$v: configure FAIL"
	exit 1
    fi
    ./waf
    if [ "$?" != "0" ]; then
        echo "$v: build FAIL"
	exit 1
    fi
    echo "$v: PASS"
done

