#!/usr/bin/python

import os
import shutil

def command(c):
    os.system(c)
    print c

def current_version():
    f = open('wscript', 'rw')
    while 1:
        l = f.readline()
        if l == '':
            break

        s = l.split()
        if len(s) == 3 and s[0] == "VERSION":
            return s[2][1:-1]

    assert(false)

v = current_version()

command("./builds/windows-32")
shutil.copy(os.path.join('build', 'windows', 'DVD-o-matic %s 32-bit Installer.exe' % v), '.')
command("./builds/windows-64")
shutil.copy(os.path.join('build', 'windows', 'DVD-o-matic %s 64-bit Installer.exe' % v), '.')
command("./waf dist")
