def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.name   = 'libdvdomatic-gtk'
    obj.includes = [ '..' ]
    obj.export_includes = ['.']
    obj.uselib = 'GLIB GTKMM CAIROMM'
    obj.source = """
                 alignment.cc
		 config_dialog.cc
		 dcp_range_dialog.cc
		 film_editor.cc
                 film_list.cc
                 film_player.cc
		 film_viewer.cc
		 filter_dialog.cc
		 filter_view.cc
		 gpl.cc
		 job_manager_view.cc
		 gtk_util.cc
                 job_wrapper.cc
		 """
    obj.target = 'dvdomatic-gtk'
