subscribers.Add (wxT ("Stephen van Vuuren (SV2DCP)"));
subscribers.Add (wxT ("Mark Allender"));
subscribers.Add (wxT ("Luiz Amoasei"));
subscribers.Add (wxT ("Sem Rumo - Projetos Audiovisuais"));
subscribers.Add (wxT ("Central Cinema"));
subscribers.Add (wxT ("Gerard Elmore"));
subscribers.Add (wxT ("Barak Epstein"));
subscribers.Add (wxT ("Bears Rebecca Fonte"));
subscribers.Add (wxT ("José Delio Ares García"));
subscribers.Add (wxT ("Glyndebourne"));
subscribers.Add (wxT ("Luke Granger-Brown"));
subscribers.Add (wxT ("Film.Ca Inc."));
subscribers.Add (wxT ("Lichtspiele Kalk"));
subscribers.Add (wxT ("Zbigniew Kamiński"));
subscribers.Add (wxT ("Timm Kröger"));
subscribers.Add (wxT ("Carlos Lagido"));
subscribers.Add (wxT ("Ross Meyer"));
subscribers.Add (wxT ("Austrian Film Museum"));
subscribers.Add (wxT ("LightBender Post"));
subscribers.Add (wxT ("Andres Sanchez"));
subscribers.Add (wxT ("Irving Shapiro"));
subscribers.Add (wxT ("Jussi Siponen"));
subscribers.Add (wxT ("Jeremy Spracklen"));
subscribers.Add (wxT ("John B. Thomas"));
subscribers.Add (wxT ("Videographe"));
