subscribers.Add (wxT ("Sem Rumo - Projetos Audiovisuais"));
subscribers.Add (wxT ("LightBenders Color Grading Boutique"));
subscribers.Add (wxT ("Central Cinema"));
subscribers.Add (wxT ("Gerard Elmore"));
subscribers.Add (wxT ("Barak Epstein"));
subscribers.Add (wxT ("José Delio Ares García"));
subscribers.Add (wxT ("Glyndebourne"));
subscribers.Add (wxT ("Film.Ca Inc."));
subscribers.Add (wxT ("Lichtspiele Kalk"));
subscribers.Add (wxT ("Timm Kröger"));
subscribers.Add (wxT ("Carlos Lagido"));
subscribers.Add (wxT ("Ross Meyer"));
subscribers.Add (wxT ("Austrian Film Museum"));
subscribers.Add (wxT ("Irving Shapiro"));
subscribers.Add (wxT ("Alex Shultz"));
subscribers.Add (wxT ("Jussi Siponen"));
subscribers.Add (wxT ("Jeremy Spracklen"));
subscribers.Add (wxT ("John B. Thomas"));
