subscribers.Add (wxT ("Mark Allender"));
subscribers.Add (wxT ("Luiz Amoasei"));
subscribers.Add (wxT ("Sem Rumo - Projetos Audiovisuais"));
subscribers.Add (wxT ("Central Cinema"));
subscribers.Add (wxT ("Drop-Out Cinema"));
subscribers.Add (wxT ("Root & Rust Creative"));
subscribers.Add (wxT ("Chris Eller"));
subscribers.Add (wxT ("Gerard Elmore"));
subscribers.Add (wxT ("Barak Epstein"));
subscribers.Add (wxT ("José Delio Ares García"));
subscribers.Add (wxT ("Glyndebourne"));
subscribers.Add (wxT ("Luke Granger-Brown"));
subscribers.Add (wxT ("Sky Hopinka"));
subscribers.Add (wxT ("Film.Ca Inc."));
subscribers.Add (wxT ("Lichtspiele Kalk"));
subscribers.Add (wxT ("Zbigniew Kamiński"));
subscribers.Add (wxT ("Timm Kröger"));
subscribers.Add (wxT ("Pilotkino LLC"));
subscribers.Add (wxT ("Carlos Lagido"));
subscribers.Add (wxT ("LightBender Post"));
subscribers.Add (wxT ("Ross Meyer"));
subscribers.Add (wxT ("Owen Morgan"));
subscribers.Add (wxT ("Austrian Film Museum"));
subscribers.Add (wxT ("Irving Shapiro"));
subscribers.Add (wxT ("Jussi Siponen"));
subscribers.Add (wxT ("Jeremy Spracklen"));
subscribers.Add (wxT ("John B. Thomas"));
subscribers.Add (wxT ("屹  崔"));
