#!/bin/bash

mkdir -p errors

pofilter -i src/lib/po -o errors/lib --nofuzzy \
    -t escapes -t nplurals -t printf -t pythonbraceformat -t variables -t xmltags \
    -t accelerators

pofilter -i src/wx/po -o errors/wx --nofuzzy \
    -t escapes -t nplurals -t printf -t pythonbraceformat -t variables -t xmltags \
    -t accelerators

pofilter -i src/tools/po -o errors/tools --nofuzzy \
    -t escapes -t nplurals -t printf -t pythonbraceformat -t variables -t xmltags \
    -t accelerators
