#!/usr/bin/python3

import sys

TICKS = 96000

in_time = int(sys.stdin.readline())
h = in_time // (TICKS * 60 * 60)
in_time -= h * (TICKS * 60 * 60)
m = in_time // (TICKS * 60)
in_time -= m * (TICKS * 60)
s = in_time // TICKS
in_time -= s * TICKS

print('%02d:%02d:%02d' % (h, m, s))
