#!/usr/bin/python

import sys

if len(sys.argv) < 2:
    print>>sys.stderr,'Syntax %s <log>' % sys.argv[0]
    sys.exit(1)

tests = {}

with open(sys.argv[1]) as f:
    while True:
        l = f.readline()
        if l == '':
            break

        s = l.split()
        if len(s) == 7 and s[6][-3:] == 'mks':
            tests[float(s[6][:-3]) / 1000000] = s[3][1:-2]

for x in sorted(tests):
    print x,tests[x]
