#!/usr/bin/python

import sys

if len(sys.argv) < 2:
    print>>sys.stderr,'Syntax %s <log>' % sys.argv[0]
    sys.exit(1)

tests = {}

with open(sys.argv[1]) as f:
    while True:
        l = f.readline()
        if l == '':
            break

        s = l.split()
        if len(s) > 2 and s[1] == 'Leaving' and s[7][-2:] == 'us':
            tests[float(s[7][:-2]) / 1000000] = s[4][1:-2]

def hms(x):
    h = int(x) // 3600
    x -= h * 3600
    m = int(x) // 60
    x -= m * 60
    return '%02d:%02d:%02d' % (h, m, x)

for x in sorted(tests):
    print hms(x),tests[x]
