usr/local/share/locale/de/LC_MESSAGES/wxstd.mo usr/share/locale/de/LC_MESSAGES/dcpomatic-wxstd.mo
usr/local/share/locale/es/LC_MESSAGES/wxstd.mo usr/share/locale/es/LC_MESSAGES/dcpomatic-wxstd.mo
usr/local/share/locale/fr/LC_MESSAGES/wxstd.mo usr/share/locale/fr/LC_MESSAGES/dcpomatic-wxstd.mo
usr/local/share/locale/it/LC_MESSAGES/wxstd.mo usr/share/locale/it/LC_MESSAGES/dcpomatic-wxstd.mo
usr/local/share/locale/sv/LC_MESSAGES/wxstd.mo usr/share/locale/sv/LC_MESSAGES/dcpomatic-wxstd.mo
usr/local/share/locale/nl/LC_MESSAGES/wxstd.mo usr/share/locale/nl/LC_MESSAGES/dcpomatic-wxstd.mo
