#!/bin/bash -e

OUT=/home/carl/public_html/carlh.net/software/dvdomatic

./waf dist

mkdir -p $OUT
mkdir -p $OUT/12.04-32
mkdir -p $OUT/12.04-64
mkdir -p $OUT/12.10-32
mkdir -p $OUT/12.10-64

builds/all-deb
cp build/deb/12.04-32/*.deb $OUT/12.04-32/
cp build/deb/12.04-64/*.deb $OUT/12.04-64/
cp build/deb/12.10-32/*.deb $OUT/12.10-32/
cp build/deb/12.10-64/*.deb $OUT/12.10-64/

builds/windows-32
cp build/windows/DVD*.exe $OUT/
builds/windows-64
cp build/windows/DVD*.exe $OUT/


