#!/bin/bash -e

UBUNTU_VERSION=$1
BITS=$2
if [ "$UBUNTU_VERSION" == "" -o "$BITS" == "" ]; then
  echo "Syntax: $0 <ubuntu version> <bits>"
  exit 1
fi

if [ "$BITS" == 32 ]; then
  CPU=i386
else
  CPU=amd64
fi

cp builds/control-$UBUNTU_VERSION debian/control
./waf dist
TARBALL=`ls -1 *.tar.bz2`
VERSION=`echo $TARBALL | sed -e 's/^dvdomatic-\(.*\).tar.bz2/\1/'`

echo "dvdomatic_$VERSION-1_$CPU.deb video extra" > debian/files

rm -rf build/deb
mkdir -p build/deb
cd build/deb
mv ../../*.tar.bz2 .
DEB_TARBALL="dvdomatic_$VERSION.orig.tar.bz2"
echo "Renaming $TARBALL to $DEB_TARBALL"
mv $TARBALL $DEB_TARBALL
tar xjf $DEB_TARBALL
cd dvdomatic-*
dpkg-source -b .
dpkg-buildpackage
cp ../*.deb ../../../
