#!/bin/bash

UBUNTU_VERSION=$1
BITS=$2
if [ "$UBUNTU_VERSION" == "" -o "$BITS" == "" ]; then
  echo "Syntax: $0 <ubuntu version> <bits>"
  exit 1
fi

ID=$UBUNTU_VERSION-$BITS
CHROOT=/home/carl/Environments/ubuntu-$ID
TARBALL=`ls -1 *.tar.bz2`
VERSION=`echo $TARBALL | sed -e 's/^dvdomatic-\(.*\).tar.bz2/\1/'`

echo "ID: $ID"
echo "chroot: $CHROOT"
echo "tarball: $TARBALL"
echo "version: $VERSION"

sudo cp *.tar.bz2 $CHROOT/root/
sudo schroot -c "ubuntu-$ID" -d /root -u root -- /bin/sh -c "tar xjf dvdomatic-$VERSION.tar.bz2 && cd dvdomatic-$VERSION && builds/chroot-deb $UBUNTU_VERSION"
mkdir -p build/deb/$ID/
echo "Copying $CHROOT/root/dvdomatic-$VERSION/build/deb/dvdomatic_$VERSION-1_i386.deb to build/deb/$ID"
sudo cp $CHROOT/root/dvdomatic-$VERSION/build/deb/dvdomatic_$VERSION-1_i386.deb build/deb/$ID

