def configure(conf):
    conf.check_cfg(package = '', path = 'wx-config', args = '--cppflags --cxxflags --libs', uselib_store = 'WXWIDGETS', mandatory = True)

def build(bld):
    obj = bld(features = 'cxx cxxprogram')
    obj.name   = 'dvdomatic-wx'
    obj.includes = [ '..' ]
    obj.export_includes = ['.']
    obj.uselib = 'WXWIDGETS'
    obj.use = 'dvdomatic'
    obj.source = """
                 dvdomatic.cc
                 film_viewer.cc
                 film_editor.cc
		 """
    obj.target = 'dvdomatic-wx'
