#!/bin/bash

set -e

ENV=/Users/carl/Environments/osx/10.6/64
DEPS=/Users/carl/dcpomatic-deps

export PKG_CONFIG_PATH=$DEPS/lib/pkgconfig:$ENV/lib/pkgconfig:/usr/lib/pkgconfig
export LINKFLAGS="-L$ENV/lib"
export CXXFLAGS="-I$ENV/include"
export PATH=$PATH:$ENV/bin
export MACOSX_DEPLOYMENT_TARGET=10.6
./waf $*

