#!/bin/bash

set -e

ENV=/Users/carl/Environments/osx/64
DEPS=/Users/carl/cdist/64

export PKG_CONFIG_PATH=$DEPS/lib/pkgconfig:$ENV/lib/pkgconfig:/usr/lib/pkgconfig
export LINKFLAGS="-L$ENV/lib"
export CXXFLAGS="-I$ENV/include"
export PATH=$PATH:$ENV/bin
./waf $*

