#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $DIR/environment
binary=build/src/tools/dcpomatic2_player

if [[ "$(uname -m)" == arm64 ]]; then
    env=arm64/11.0
else
    env=x86_64/10.10
fi

export DYLD_LIBRARY_PATH=/Users/cah/osx-environment/$env/lib:/usr/local/lib

# Allow running from a tree built using cdist
export LD_LIBRARY_PATH=$DIR/../../../lib:$DIR/../../../lib64:$LD_LIBRARY_PATH

if [ "$1" == "--debug" ]; then
    shift
    gdb --args build/src/tools/dcpomatic2_player $*
elif [ "$1" == "--valgrind" ]; then
    shift
    valgrind --tool="memcheck" --suppressions=suppressions --track-fds=yes --leak-check=full --show-reachable=yes $binary $*
elif [ "$1" == "--callgrind" ]; then
    shift
    valgrind --tool="callgrind" $binary $*
elif [ "$1" == "--massif" ]; then
    shift
    valgrind --tool="massif" $binary $*
elif [ "$1" == "--i18n" ]; then
    shift
    LANGUAGE=fr_FR.UTF8 LANG=fr_FR.UTF8 LC_ALL=fr_FR.UTF8 $binary "$*"
elif [ "$1" == "--perf" ]; then
    shift
    perf record $binary $*
elif [ "$1" == "--screenshot" ]; then
    shift
    GTK_PATH=/usr/local/lib/gtk-3.0 GTK_MODULES=gtk-vector-screenshot $binary "$*"
else
    $binary $*
fi
