#!/bin/bash

export LD_LIBRARY_PATH=build/src/lib:build/src/wx:/home/c.hetherington/lib:$LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=build/src/lib:build/src/wx:/carl/Environment/64/lib
if [ "$1" == "--debug" ]; then
    shift
    gdb --args build/src/tools/dcpomatic2_kdm $*
elif [ "$1" == "--valgrind" ]; then
    shift
    valgrind --tool="memcheck" build/src/tools/dcpomatic2_kdm $*
elif [ "$1" == "--callgrind" ]; then
    shift
    valgrind --tool="callgrind" build/src/tools/dcpomatic2_kdm $*
elif [ "$1" == "--massif" ]; then
    shift
    valgrind --tool="massif" build/src/tools/dcpomatic2_kdm $*
elif [ "$1" == "--i18n" ]; then
    shift
    LANGUAGE=fr_FR.UTF8 LANG=fr_FR.UTF8 LC_ALL=fr_FR.UTF8 build/src/tools/dcpomatic2_kdm "$*"
elif [ "$1" == "--perf" ]; then
    shift
    perf record build/src/tools/dcpomatic2_kdm $*
else
    build/src/tools/dcpomatic2_kdm $*
fi
