#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $DIR/environment
binary=build/src/tools/dcpomatic2_player

if [ "$1" == "--debug" ]; then
    shift
    gdb --args build/src/tools/dcpomatic2_player $*
elif [ "$1" == "--valgrind" ]; then
    shift
    valgrind --tool="memcheck" --suppressions=suppressions --track-fds=yes $binary $*
elif [ "$1" == "--callgrind" ]; then
    shift
    valgrind --tool="callgrind" $binary $*
elif [ "$1" == "--massif" ]; then
    shift
    valgrind --tool="massif" $binary $*
elif [ "$1" == "--i18n" ]; then
    shift
    LANGUAGE=fr_FR.UTF8 LANG=fr_FR.UTF8 LC_ALL=fr_FR.UTF8 $binary "$*"
elif [ "$1" == "--perf" ]; then
    shift
    perf record $binary $*
else
    $binary $*
fi
