#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $DIR/environment

if [ "$1" == "--debug" ]; then
    shift
    gdb --args build/src/tools/dcpomatic2_combiner $*
elif [ "$1" == "--valgrind" ]; then
    shift
    valgrind --tool="memcheck" --suppressions=suppressions --track-fds=yes build/src/tools/dcpomatic2_combiner $*
elif [ "$1" == "--callgrind" ]; then
    shift
    valgrind --tool="callgrind" build/src/tools/dcpomatic2_combiner $*
elif [ "$1" == "--massif" ]; then
    shift
    valgrind --tool="massif" build/src/tools/dcpomatic2_combiner $*
elif [ "$1" == "--i18n" ]; then
    shift
    LANGUAGE=fr_FR.UTF8 LANG=fr_FR.UTF8 LC_ALL=fr_FR.UTF8 build/src/tools/dcpomatic2_combiner "$*"
elif [ "$1" == "--perf" ]; then
    shift
    perf record build/src/tools/dcpomatic2_combiner $*
else
    build/src/tools/dcpomatic2_combiner $*
fi
