#!/bin/bash

export LD_LIBRARY_PATH=build/src/lib:build/src/wx:build/src/asdcplib/src:$LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=build/src/lib:build/src/wx:build/src/asdcplib/src:/carl/Environment/64/lib
if [ "$1" == "--debug" ]; then
    shift
    gdb --args build/src/tools/dcpomatic2 $*
elif [ "$1" == "--valgrind" ]; then
    shift
    valgrind --tool="memcheck" build/src/tools/dcpomatic2 $*
elif [ "$1" == "--callgrind" ]; then
    shift
    valgrind --tool="callgrind" build/src/tools/dcpomatic2 $*
elif [ "$1" == "--massif" ]; then
    shift
    valgrind --tool="massif" build/src/tools/dcpomatic2 $*
elif [ "$1" == "--i18n" ]; then
    shift
    LANGUAGE=fr_FR.UTF8 LANG=fr_FR.UTF8 LC_ALL=fr_FR.UTF8 build/src/tools/dcpomatic2 "$*"
elif [ "$1" == "--perf" ]; then
    shift
    perf record build/src/tools/dcpomatic2 $*
else
    build/src/tools/dcpomatic2 $*
fi
