#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $DIR/environment

if [ "$1" == "--debug" ]; then
    gdb --args build/src/tools/dcpomatic2_server
elif [ "$1" == "--valgrind" ]; then
    valgrind --tool="memcheck" build/src/tools/dcpomatic2_server
else
    build/src/tools/dcpomatic2_server
fi
