#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $DIR/environment

if [ "$1" == "--debug" ]; then
    shift
    gdb --args build/src/tools/dcpomatic2_create $*
elif [ "$1" == "--valgrind" ]; then
    shift
    valgrind --tool="memcheck" build/src/tools/dcpomatic2_create $*
elif [ "$1" == "--callgrind" ]; then
    shift
    valgrind --tool="callgrind" build/src/tools/dcpomatic2_create $*
elif [ "$1" == "--perf" ]; then
    shift
    perf record build/src/tools/dcpomatic2_create $*
else
    build/src/tools/dcpomatic2_create "$@"
fi
