#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $DIR/environment

if [ "$1" == "--debug" ]; then
    shift
    gdb --args build/src/tools/dcpomatic2_map "$@"
elif [ "$1" == "--valgrind" ]; then
    shift
    valgrind --tool="memcheck" --leak-check=full --show-reachable=yes build/src/tools/dcpomatic2_map "$@"
else
    build/src/tools/dcpomatic2_map "$@"
fi
