#!/bin/bash

export LD_LIBRARY_PATH=build/src/lib:$LD_LIBRARY_PATH:build/src
if [ "$1" == "--debug" ]; then
    shift
    gdb --args build/src/tools/dcpomatic_kdm "$@"
elif [ "$1" == "--valgrind" ]; then
    shift
    valgrind --tool="memcheck" --leak-check=full --show-reachable=yes build/src/tools/dcpomatic_kdm "$@"
else
    build/src/tools/dcpomatic_kdm "$@"
fi
