#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $DIR/environment

if [ "$1" == "--debug" ]; then
    shift
    gdb --args build/src/tools/dcpomatic2_kdm $*
elif [ "$1" == "--valgrind" ]; then
    shift
    valgrind --tool="memcheck" build/src/tools/dcpomatic2_kdm $*
elif [ "$1" == "--callgrind" ]; then
    shift
    valgrind --tool="callgrind" build/src/tools/dcpomatic2_kdm $*
elif [ "$1" == "--massif" ]; then
    shift
    valgrind --tool="massif" build/src/tools/dcpomatic2_kdm $*
elif [ "$1" == "--i18n" ]; then
    shift
    LANGUAGE=ru_RU.UTF8 LANG=ru_RU.UTF8 LC_ALL=ru_RU.UTF8 build/src/tools/dcpomatic2_kdm $*
elif [ "$1" == "--perf" ]; then
    shift
    perf record build/src/tools/dcpomatic2_kdm $*
elif [ "$1" == "--screenshot" ]; then
    shift
    GTK_PATH=/usr/local/lib/gtk-3.0 GTK_MODULES=gtk-vector-screenshot build/src/tools/dcpomatic2_kdm $*
else
    build/src/tools/dcpomatic2_kdm $*
fi
