#!/bin/bash

export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:build/src/lib:build/src:/Users/carl/Environments/osx/10.8/lib
if [ "$1" == "--debug" ]; then
    shift
    gdb --args build/src/tools/dvdomatic "$*"
elif [ "$1" == "--valgrind" ]; then
    shift
    valgrind --tool="memcheck" build/src/tools/dvdomatic $*
elif [ "$1" == "--i18n" ]; then
    shift
    LANGUAGE=fr_FR.UTF8 LANG=fr_FR.UTF8 build/src/tools/dvdomatic "$*"
else
    build/src/tools/dvdomatic "$*"
fi
