#!/bin/bash

export LD_LIBRARY_PATH=build/src/lib:$LD_LIBRARY_PATH:build/src
if [ "$1" == "--debug" ]; then
    shift
    gdb --args build/src/tools/makedcp "$@"
elif [ "$1" == "--memcheck" ]; then
    shift
    valgrind --tool="memcheck" --leak-check=full --show-reachable=yes build/src/tools/makedcp "$@"
elif [ "$1" == "--massif" ]; then
    shift
    valgrind --tool="massif" build/src/tools/makedcp "$@"
else
    build/src/tools/makedcp "$@"
fi
