#!/bin/bash

export LD_LIBRARY_PATH=build/src/lib:$LD_LIBRARY_PATH
if [ "$1" == "--debug" ]; then
    gdb --args build/src/tools/servomatic_cli
elif [ "$1" == "--valgrind" ]; then
    valgrind --tool="memcheck" build/src/tools/servomatic_cli
else
    build/src/tools/servomatic_cli
fi
