#!/bin/bash

export LD_LIBRARY_PATH=build/src/lib:$LD_LIBRARY_PATH
if [ "$1" == "--debug" ]; then
    shift
    gdb --args build/src/tools/servomatictest $*
elif [ "$1" == "--valgrind" ]; then
    shift
    valgrind --tool="memcheck" build/src/tools/servomatictest $*
else
    build/src/tools/servomatictest $*
fi
