#!/bin/bash

export LD_LIBRARY_PATH=build/src/lib:$LD_LIBRARY_PATH
if [ "$1" == "--debug" ]; then
    gdb --args build/src/tools/servomatic_gui
elif [ "$1" == "--valgrind" ]; then
    valgrind --tool="memcheck" build/src/tools/servomatic_gui
else
    build/src/tools/servomatic_gui
fi
