#!/bin/bash

export LD_LIBRARY_PATH=build/src/lib:$LD_LIBRARY_PATH
if [ "$1" == "--debug" ]; then
    gdb --args build/test/short-unit-tests
elif [ "$1" == "--valgrind" ]; then
    valgrind --tool="memcheck" --leak-check=full build/test/short-unit-tests
else
    build/test/short-unit-tests
fi

