#!/bin/bash
#
# e.g. --run_tests=foo

export LD_LIBRARY_PATH=build/src/lib:/home/c.hetherington/lib:$LD_LIBRARY_PATH
if [ "$1" == "--debug" ]; then
    shift;
    gdb --args build/test/unit-tests --catch_system_errors=no --log_level=test_suite $*
elif [ "$1" == "--backtrace" ]; then
    shift;
    gdb -batch -ex "run" -ex "thread apply all bt" -return-child-result --args build/test/unit-tests --catch_system_errors=yes $*
elif [ "$1" == "--valgrind" ]; then
    shift;
#    valgrind --tool="memcheck" --vgdb=yes --vgdb-error=0 build/test/unit-tests $*
    valgrind --tool="memcheck" --suppressions=suppressions build/test/unit-tests $*
elif [ "$1" == "--callgrind" ]; then
    shift;
    valgrind --tool="callgrind" build/test/unit-tests $*
elif [ "$1" == "--quiet" ]; then
    shift;
    build/test/unit-tests --catch_system_errors=no $*
elif [ "$1" == "--drd" ]; then
    shift;
    valgrind --tool="drd" build/test/unit-tests $*
elif [ "$1" == "--helgrind" ]; then
    shift;
    valgrind --tool="helgrind" build/test/unit-tests $*
else
    ulimit -c unlimited
    build/test/unit-tests --catch_system_errors=no --log_level=test_suite $*
#    build/test/unit-tests --catch_system_errors=no $*
fi
