#!/bin/bash
#
# e.g. --run_tests=foo

export LD_LIBRARY_PATH=build/src/lib:$LD_LIBRARY_PATH
export DCPOMATIC_LINUX_SHARE_PREFIX=`pwd`
if [ "$1" == "--debug" ]; then
    shift;
    gdb --args build/test/unit-tests --catch_system_errors=no $*
elif [ "$1" == "--valgrind" ]; then
    shift;
    valgrind --tool="memcheck" --leak-check=full build/test/unit-tests $*
else
    build/test/unit-tests --catch_system_errors=no $*
fi

