def configure(conf):
    conf.recurse('tools')
    if not conf.env.DISABLE_GUI:
        conf.recurse('wx')

def build(bld):
    bld.recurse('lib')
    bld.recurse('tools')
    if not bld.env.DISABLE_GUI:
        bld.recurse('wx')

def pot(bld):
    bld.recurse('lib')
    bld.recurse('wx')
    bld.recurse('tools')

def pot_merge(bld):
    bld.recurse('lib')
    bld.recurse('wx')
    bld.recurse('tools')
