import os
import glob
from waflib import Logs
import i18n

def build(bld):
    for t in ['makedcp', 'servomatic_cli', 'servomatictest']:
        obj = bld(features = 'cxx cxxprogram')
        obj.uselib = 'BOOST_THREAD OPENJPEG DCP AVFORMAT AVFILTER AVCODEC AVUTIL SWSCALE POSTPROC CXML WXWIDGETS'
        obj.includes = ['..']
        obj.use    = ['libdvdomatic']
        obj.source = '%s.cc' % t
        obj.target = t

    if not bld.env.DISABLE_GUI:
        for t in ['dvdomatic', 'dvdomatic_batch', 'servomatic_gui']:
            obj = bld(features = 'cxx cxxprogram')
            obj.uselib = 'DCP OPENJPEG AVFORMAT AVFILTER AVCODEC AVUTIL SWSCALE POSTPROC CXML WXWIDGETS'
            if bld.env.STATIC:
                obj.uselib += ' GTK'
            obj.includes = ['..']
            obj.use    = ['libdvdomatic', 'libdvdomatic-wx']
            obj.source = '%s.cc' % t
            if bld.env.TARGET_WINDOWS:
                obj.source += ' ../../platform/windows/dvdomatic.rc'
            obj.target = t

        i18n.po_to_mo(os.path.join('src', 'tools'), 'dvdomatic', bld)

def pot(bld):
    i18n.pot(os.path.join('src', 'tools'), 'dvdomatic.cc', 'dvdomatic')

def pot_merge(bld):
    i18n.pot_merge(os.path.join('src', 'tools'), 'dvdomatic')
