def build(bld):
    for t in ['makedcp', 'servomatic_cli', 'servomatictest']:
        obj = bld(features = 'cxx cxxprogram')
        obj.uselib = 'BOOST_THREAD OPENJPEG DCP AVFORMAT AVFILTER AVCODEC AVUTIL SWSCALE POSTPROC'
        obj.includes = ['..']
        obj.use    = ['libdvdomatic']
        obj.source = '%s.cc' % t
        obj.target = t

    if not bld.env.DISABLE_GUI:
        for t in ['dvdomatic', 'servomatic_gui']:
            obj = bld(features = 'cxx cxxprogram')
            obj.uselib = 'DCP OPENJPEG AVFORMAT AVFILTER AVCODEC AVUTIL SWSCALE POSTPROC'
            obj.includes = ['..']
            obj.use    = ['libdvdomatic', 'libdvdomatic-wx']
            obj.source = '%s.cc' % t
            if bld.env.TARGET_WINDOWS:
                obj.source += ' ../../windows/dvdomatic.rc'
            obj.target = t
